const Actions = {
  ADD_HIGHLIGHTED_ORBITAL: 'ADD_HIGHLIGHTED_ORBITAL',
  CAMERA_PANNED: 'CAMERA_PANNED',
  MODAL_ACTIVE: 'MODAL_ACTIVE',
  REMOVE_HIGHLIGHTED_ORBITAL: 'REMOVE_HIGHLIGHTED_ORBITAL',
  SCALE_CHANGE: 'SCALE_CHANGE',
  SETTINGS_ACTIVE: 'SETTINGS_ACTIVE',
  SET_ACTIVE_ORBITAL: 'SET_ACTIVE_ORBITAL',
  SET_CAMERA_ORBIT: 'SET_CAMERA_ORBIT',
  SET_LABEL_TEXT: 'SET_LABEL_TEXT',
  SET_ORBITAL_DATA: 'SET_ORBITAL_DATA',
  SET_PAGE_TEXT: 'SET_PAGE_TEXT',
  SET_PERCENT_LOADED: 'SET_PERCENT_LOADED',
  SET_PLAYING: 'SET_PLAYING',
  SET_POSITION: 'SET_POSITION',
  SET_RELEASED: 'SET_RELEASED',
  SET_TEXTURE_LOADED: 'SET_TEXTURE_LOADED',
  SET_TIME: 'SET_TIME',
  SET_TOUCHED: 'SET_TOUCHED',
  SET_UI_CONTROLS: 'SET_UI_CONTROLS',
  SET_VOLUME: 'SET_VOLUME',
  SHOW_LABEL: 'SHOW_LABEL',
  SPEED_CHANGE: 'SPEED_CHANGE',
  TIME_OFFSET_CHANGE: 'TIME_OFFSET_CHANGE',
  TOUR_COMPLETED: 'TOUR_COMPLETED',
  TOUR_SKIPPED: 'TOUR_SKIPPED',
  ZOOM_CHANGE: 'ZOOM_CHANGE'
} as const

export type ActionType = (typeof Actions)[keyof typeof Actions]

export default Actions
